import:
    - 'configs/base.yaml'
package:
    - 'charnet.modeling.model'
    - 'data.data_loader'
    - 'data.image_dataset'
    - 'data.synth_dataset'
define:
  - name: train_data
    class: ImageDataset
    data_dir:
        - '/home/robtu/Github/data/icdar2015'
        #- './datasets/icdar2015/'
    data_list:
        - '/home/robtu/Github/data/icdar2015/train_list.txt'
        #- './datasets/icdar2015/train_list.txt'
    processes:
        - class: AugmentDetectionData
          augmenter_args:
              - ['Fliplr', 0.5]
              - {'cls': 'Affine', 'rotate': [-10, 10]}
              - ['Resize', [0.5, 3.0]]
          only_resize: False
          keep_ratio: False
        - class: RandomCropData
          size: [640, 640]
          max_tries: 10
        - class: MakeICDARData
        - class: MakeSegDetectionData
        - class: MakeBorderMap
        - class: NormalizeImage
        - class: FilterKeys
          superfluous: ['polygons', 'filename', 'shape', 'ignore_tags', 'is_training']


  - name: train_data_synth
    class: SynthDataset
    data_dir:
        - '/home/robtu/Github/data/SynthText/SynthText/'
        #- './datasets/icdar2015/'
    mat_list:
        - '/home/robtu/Github/data/SynthText/SynthText/gtsub.mat'
        #- './datasets/icdar2015/train_list.txt'
    processes:
        - class: AugmentDetectionData
          augmenter_args:
              - ['Fliplr', 0.5]
              - {'cls': 'Affine', 'rotate': [-10, 10]}
              - ['Resize', [0.5, 3.0]]
          only_resize: False
          keep_ratio: False
        - class: RandomCropData
          size: [640, 640]
          max_tries: 10
        - class: MakeICDARData
#        - class: MakeSegDetectionData
        - class: MakeBorderMap
          charindx: 'datasets/ICDAR2015/test/char_dict.txt'  
          yamlfile: 'datasets/ICDAR2015/test/rect_bbox.yaml'
        - class: NormalizeImage
          norm_type: 'lib'
        - class: FilterKeys
#          superfluous: [ 'filename', 'shape', 'ignore_tags', 'is_training',  'ignore_tags_char']
          #superfluous: ['polygons', 'filename', 'shape', 'ignore_tags', 'is_training', 'polygons_char', 'ignore_tags_char', 'thresh_mask_char', 'thresh_map_char', 'thresh_mask', 'thresh_map', 'mask', 'gt_char', 'mask_char', 'gt', 'ignore_tags_char', 'polygons_char']
          superfluous: ['polygons', 'filename', 'shape', 'ignore_tags', 'is_training',  'ignore_tags_char', 'ignore_tags_char']
    mode: "train"

  - name: validate_data
    class: ImageDataset
    data_dir:
        - './datasets/icdar2015/'
    data_list:
        - './datasets/icdar2015/test_list.txt'
    processes:
        - class: AugmentDetectionData
          augmenter_args:
              # - ['Resize', {'width': 1280, 'height': 736}]
              - ['Resize', {'width': 2048, 'height': 1152}]
          only_resize: True
          keep_ratio: True
        - class: MakeICDARData
        - class: MakeSegDetectionData
        - class: NormalizeImage

  - name: 'Experiment'
    train: 
        class: TrainSettings
        data_loader: 
            class: DataLoader
            dataset: ^train_data
            batch_size: 16
            num_workers: 16
        epochs: 12
    train_synth: 
        class: TrainSettings
        data_loader: 
            class: DataLoader
            dataset: ^train_data_synth
            batch_size: 1
            num_workers: 1
        epochs: 12
        
        
        
        
        
        
        
        